#!/usr/bin/env python3
"""Regenerate the presentation's embedded assets from the app's own files.

  css/fonts.css     Inter (the app's typeface) inlined as data URIs, so the page renders it
                    even from file:// (font loads are CORS-checked there).
  assets/brand.js   the mark and wordmark SVGs, inlined for JS.

Run from anywhere:  python3 presentation/tools/build-assets.py
"""
import base64
import json
import re
from pathlib import Path

HERE = Path(__file__).resolve().parent.parent
REPO = HERE.parent

# Inter, the app's own typeface (static/, as ui/css/base.css declares it), embedded so the
# page renders it from file:// too. Unicode ranges are copied from base.css.
base = (REPO / "ui" / "css" / "base.css").read_text()
out = ["/* Inter, embedded as data URIs so the page also works from file:// (font loads are "
       "CORS-checked there). Generated by tools/build-assets.py from static/ and ui/css/base.css. */"]
for face in re.findall(r"@font-face\{[^}]*\}", base):
    name = re.search(r'url\("([^"]+)"\)', face).group(1)
    data = base64.b64encode((REPO / "static" / name).read_bytes()).decode()
    out.append(face.replace(f'url("{name}")', f"url(data:font/woff2;base64,{data})").replace("font-display:swap", "font-display:block"))
(HERE / "css" / "fonts.css").write_text("\n".join(out) + "\n")

mark_svg = (REPO / "static" / "applicable-mark.svg").read_text()
mark = re.search(r"<rect.*?/>\s*<path[^>]*/>", mark_svg, re.S).group(0)
lockup = (REPO / "static" / "applicable-lockup.svg").read_text()
word = lockup[lockup.index("</g>") + 4:lockup.rindex("</svg>")]

# Bounding box of the wordmark paths (absolute M/L/H/V/Q commands).
xs, ys = [], []
for _, d in re.findall(r'<path fill="([^"]+)" d="([^"]+)"', word):
    cmd, buf = None, []
    for tok in re.findall(r"[A-Za-z]|-?\d+\.?\d*", d):
        if tok.isalpha():
            cmd, buf = tok, []
            continue
        buf.append(float(tok))
        if cmd == "H":
            xs.append(buf.pop())
        elif cmd == "V":
            ys.append(buf.pop())
        elif len(buf) == 2:
            xs.append(buf[0])
            ys.append(buf[1])
            buf = []
x0, y0, w, h = min(xs) - 1, min(ys) - 1, max(xs) - min(xs) + 2, max(ys) - min(ys) + 2
word = word.replace('fill="#1F1B16"', 'fill="currentColor"').replace('fill="#B63F16"', 'fill="var(--wm-ai, #B63F16)"')

SVG = '<svg xmlns="http://www.w3.org/2000/svg" viewBox="{}" aria-hidden="true">{}</svg>'
mark_js = json.dumps(SVG.format("0 0 100 100", mark))
word_js = json.dumps(SVG.format(f"{x0:.1f} {y0:.1f} {w:.1f} {h:.1f}", word))
js = (
    "/* Generated by tools/build-assets.py from static/applicable-mark.svg and "
    "static/applicable-lockup.svg. Do not edit by hand. */\n(function (A) {\n  A.brand = {\n"
    f"    mark: {mark_js},\n"
    f"    wordmark: {word_js},\n"
    f"    wordmarkAspect: {w / h:.4f},\n  }};\n}})(window.Applicable = window.Applicable || {{}});\n"
)
(HERE / "assets" / "brand.js").write_text(js)
print(f"fonts.css: {len(out) - 1} faces · brand.js: wordmark {w:.1f}×{h:.1f}")
