#!/usr/bin/env node
/*
 * Encodes audio/soundtrack.wav to MP3 (the one compressed format every browser decodes) and
 * embeds it in assets/soundtrack.js, then *measures* how far the decoder shifts it (encoder delay) by decoding the embedded file
 * in Chromium and cross-correlating it with the WAV. The measured lead is stored next to the
 * audio and compensated at playback, so picture and sound stay frame-exact — the same idea
 * as the reference film's check-sync.py, applied to the page.
 *
 *   node tools/embed-audio.mjs          # needs ffmpeg, playwright-core, python3 + numpy
 */
import { chromium } from 'playwright-core';
import { execFileSync } from 'node:child_process';
import { readFileSync, writeFileSync, mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const wav = join(root, 'audio', 'soundtrack.wav');
const tmp = mkdtempSync(join(tmpdir(), 'aa-audio-'));
const mp3 = join(tmp, 'soundtrack.mp3');
execFileSync('ffmpeg', ['-loglevel', 'error', '-y', '-i', wav, '-c:a', 'libmp3lame', '-b:a', '192k', mp3]);
const b64 = readFileSync(mp3).toString('base64');

const write = (lead) =>
  writeFileSync(
    join(root, 'assets', 'soundtrack.js'),
    '/* Generated by tools/embed-audio.mjs from audio/soundtrack.wav (tools/soundtrack.py). Do not edit. */\n' +
      '(function (A) {\n' +
      `  A.soundtrackData = { mime: 'audio/mpeg', lead: ${lead.toFixed(5)}, base64: '${b64}' };\n` +
      '})(window.Applicable = window.Applicable || {});\n'
  );
write(0);

// Decode in the browser exactly as the page will, and hand back the first seconds.
const browser = await chromium.launch({ executablePath: process.env.CHROMIUM_PATH || undefined });
const page = await browser.newPage();
await page.goto(pathToFileURL(join(root, 'index.html')).href + '?t=0');
await page.waitForFunction(() => document.documentElement.dataset.ready === '1');
const decoded = await page.evaluate(async () => {
  const d = window.Applicable.soundtrackData;
  const bin = atob(d.base64);
  const bytes = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) bytes[i] = bin.charCodeAt(i);
  const ctx = new OfflineAudioContext(2, 48000, 48000);
  const buf = await ctx.decodeAudioData(bytes.buffer);
  const ch = buf.getChannelData(0).slice(0, buf.sampleRate * 30);
  return { rate: buf.sampleRate, length: buf.length, data: Array.from(ch) };
});
await browser.close();
const raw = join(tmp, 'decoded.json');
writeFileSync(raw, JSON.stringify(decoded));

const lead = parseFloat(
  execFileSync('python3', ['-c', `
import json, numpy as np, soundfile as sf
from scipy import signal
d = json.load(open(${JSON.stringify(raw)}))
y = np.array(d['data']); r = d['rate']
x, sr = sf.read(${JSON.stringify(wav)})
x = x[:, 0]
if sr != r:
    x = signal.resample_poly(x, r, sr)
n = min(len(x), len(y), r * 30)
c = signal.correlate(y[:n], x[:n], mode='full', method='fft')
lag = int(np.argmax(c)) - (n - 1)
print(lag / r)
`]).toString()
);
write(lead);
rmSync(tmp, { recursive: true, force: true });
console.log(`assets/soundtrack.js: ${(b64.length / 1e6).toFixed(2)} MB base64 · decoder lead ${(lead * 1000).toFixed(2)} ms (compensated at playback)`);
