"""Markup of the seven onboarding steps, taken verbatim from 00_Onboarding.html.

Generated once from the approved mockup so nothing is retyped by hand.
views/onboarding.py fills the dynamic parts (counts, selections, the story
on the card, the ranked roles) by replacing the mockup's sample values, and
places native buttons over every interactive element.

Do not reformat: the strings are compared against the mockup.
"""

# fmt: off
S_1 = """<div class="u-wrap"><div class="u-col">
<div class="w-h1">Start with your CV</div>
<div class="w-sub">We’ll read it and build your candidate profile. You review every field before anything is used.</div>
<div class="u-drop"><div class="u-doc"><svg width="24" height="24" viewBox="0 0 16 16"><path d="M8 10.5V3M5 6l3-3 3 3" stroke="#0071E3" stroke-width="1.5" fill="none" stroke-linecap="round" stroke-linejoin="round"/><path d="M2.5 10.5v2c0 .6.4 1 1 1h9c.6 0 1-.4 1-1v-2" stroke="#0071E3" stroke-width="1.5" fill="none" stroke-linecap="round"/></svg></div>
<div class="u-dt">Drop your CV here</div><div class="u-ds">PDF · up to 10 MB</div><div class="btn" style="margin-top:16px">Choose file</div></div>
<div class="w-card u-file"><span class="u-pdf">PDF</span><div style="flex:1"><div style="display:flex;justify-content:space-between"><span class="u-fn">Synthetic_CV_Giulia_Rossi.pdf</span><span class="u-fm">Reading text · 64%</span></div><div class="u-fm">184 KB · 2 pages</div><div class="u-pb"><i></i></div></div></div>
<div class="u-tr">
<div class="w-card u-t"><div class="ic"><svg viewBox="0 0 16 16"><rect x="3.5" y="7" width="9" height="6.5" rx="1.5"/><path d="M5.5 7V5a2.5 2.5 0 0 1 5 0v2"/></svg></div><b>Private by default</b><span>Used only to match you with roles.</span></div>
<div class="w-card u-t"><div class="ic"><svg viewBox="0 0 16 16"><path d="M3 8.5 6.3 12 13 4.5"/></svg></div><b>You confirm everything</b><span>Nothing is used until you review it.</span></div>
<div class="w-card u-t"><div class="ic"><svg viewBox="0 0 16 16"><path d="M3 4.5h10M6 4.5V3h4v1.5M4.5 4.5l.7 9h5.6l.7-9"/></svg></div><b>Delete anytime</b><span>Remove your CV and profile in one click.</span></div>
</div></div></div>"""

S_2 = """<div class="p-l">
<div class="w-h1">Here’s what we found</div>
<div class="w-sub">6 sections from your CV. <b>2 need a quick review</b> before we use them.</div>
<div class="p-grid">
<div class="w-card p-s rv"><div class="p-h"><div class="ic"><svg viewBox="0 0 16 16"><rect x="2" y="3" width="12" height="10" rx="1.6"/><circle cx="6" cy="7.2" r="1.6"/><path d="M3.8 11c.4-1.1 1.2-1.7 2.2-1.7s1.8.6 2.2 1.7M10 6.5h2M10 9h2"/></svg></div><b>Work authorization</b><span class="w-b am"><i></i>Review</span></div><div class="p-v">EU citizen (Italy) · China X1 study visa</div><div class="p-m">Other countries not mentioned in your CV</div><div class="p-q">Can you work anywhere else without sponsorship?</div><div class="p-act"><span class="w-chip add">+ Add a country</span><span class="w-chip">Only these</span></div><div class="p-src"><svg width="11" height="11" viewBox="0 0 16 16"><path d="M4 2h5.5L12 4.5V14H4z" stroke="#AEAEB2" stroke-width="1.6" fill="none"/></svg>Page 2 · Personal details</div></div>
<div class="w-card p-s rv"><div class="p-h"><div class="ic"><svg viewBox="0 0 16 16"><path d="M8 2 13.5 4v3.8c0 3-2.3 5.3-5.5 6.2-3.2-.9-5.5-3.2-5.5-6.2V4z"/></svg></div><b>Sponsorship</b><span class="w-b am"><i></i>Review</span></div><div class="p-v">Likely needed in China and Singapore</div><div class="p-m">Inferred from your visa — not stated in your CV</div><div class="p-q">Is this right?</div><div class="p-act"><span class="w-chip on">Yes, that’s right</span><span class="w-chip">Edit</span></div><div class="p-src"><svg width="11" height="11" viewBox="0 0 16 16"><path d="M4 2h5.5L12 4.5V14H4z" stroke="#AEAEB2" stroke-width="1.6" fill="none"/></svg>Inferred · Page 2</div></div>
<div class="w-card p-s"><div class="p-h"><div class="ic"><svg viewBox="0 0 16 16"><path d="M8 2.2 9.3 6.7 13.8 8 9.3 9.3 8 13.8 6.7 9.3 2.2 8 6.7 6.7z"/></svg></div><b>Skills</b><span class="w-b ok"><i></i>Found</span></div><div class="p-chips"><span class="w-chip">Python</span><span class="w-chip">SQL</span><span class="w-chip">Financial modelling</span><span class="w-chip">React</span><span class="w-chip">Figma</span><span class="w-chip">+6</span></div><div class="p-src"><svg width="11" height="11" viewBox="0 0 16 16"><path d="M4 2h5.5L12 4.5V14H4z" stroke="#AEAEB2" stroke-width="1.6" fill="none"/></svg>Page 1 · Skills</div></div>
<div class="w-card p-s"><div class="p-h"><div class="ic"><svg viewBox="0 0 16 16"><path d="M1.5 6 8 3l6.5 3L8 9z"/><path d="M4.5 7.5v3.2c1 1 2.2 1.5 3.5 1.5s2.5-.5 3.5-1.5V7.5"/></svg></div><b>Education</b><span class="w-b ok"><i></i>Found</span></div><div class="p-v">MSc Finance · Fudan University</div><div class="p-m">2025 – 2027 · BSc Economics, Bocconi</div><div class="p-src"><svg width="11" height="11" viewBox="0 0 16 16"><path d="M4 2h5.5L12 4.5V14H4z" stroke="#AEAEB2" stroke-width="1.6" fill="none"/></svg>Page 1 · Education</div></div>
<div class="w-card p-s"><div class="p-h"><div class="ic"><svg viewBox="0 0 16 16"><rect x="2" y="4.5" width="12" height="9" rx="1.6"/><path d="M5.5 4.5V3.2c0-.7.5-1.2 1.2-1.2h2.6c.7 0 1.2.5 1.2 1.2v1.3"/></svg></div><b>Experience</b><span class="w-b ok"><i></i>Found</span></div><div class="p-v">Business Analyst Intern · Mediobanco</div><div class="p-m">Product Intern, fintech · 10 months total</div><div class="p-src"><svg width="11" height="11" viewBox="0 0 16 16"><path d="M4 2h5.5L12 4.5V14H4z" stroke="#AEAEB2" stroke-width="1.6" fill="none"/></svg>Pages 1–2 · Experience</div></div>
<div class="w-card p-s"><div class="p-h"><div class="ic"><svg viewBox="0 0 16 16"><path d="M2.5 3.5h7M6 2v1.5M4 3.5c.5 2.5 2 4.5 4 5.5M8 3.5c-.5 2.5-2 4.5-4.5 5.5"/><path d="M9 14l2.5-6 2.5 6M9.8 12h3.4"/></svg></div><b>Languages</b><span class="w-b ok"><i></i>Found</span></div><div class="p-chips"><span class="w-chip">Italian · native</span><span class="w-chip">English · C1</span><span class="w-chip">Mandarin · HSK 4</span></div><div class="p-src"><svg width="11" height="11" viewBox="0 0 16 16"><path d="M4 2h5.5L12 4.5V14H4z" stroke="#AEAEB2" stroke-width="1.6" fill="none"/></svg>Page 2 · Languages</div></div>
</div></div>
<div class="p-r"><div class="w-lab">Your CV<span>Page 2 of 2</span></div>
<div class="p-page">
<div class="p-nm">Giulia Rossi</div><div class="p-ln" style="width:46%"></div>
<div style="height:14px"></div>
<div class="p-hl b"><span class="tg">Languages</span><div class="p-ln" style="width:70%"></div><div class="p-ln" style="width:52%"></div></div>
<div class="p-ln" style="width:94%"></div><div class="p-ln" style="width:88%"></div><div class="p-ln" style="width:76%"></div>
<div class="p-hl a"><span class="tg">Work authorization</span><div class="p-ln" style="width:84%"></div><div class="p-ln" style="width:58%"></div></div>
<div class="p-ln" style="width:92%"></div><div class="p-ln" style="width:80%"></div><div class="p-ln" style="width:86%"></div><div class="p-ln" style="width:40%"></div>
<div style="height:14px"></div>
<div class="p-hl b"><span class="tg">Experience</span><div class="p-ln" style="width:90%"></div><div class="p-ln" style="width:74%"></div><div class="p-ln" style="width:62%"></div></div>
<div class="p-ln" style="width:88%"></div><div class="p-ln" style="width:94%"></div><div class="p-ln" style="width:70%"></div><div class="p-ln" style="width:82%"></div><div class="p-ln" style="width:56%"></div>
</div></div>"""

S_3A = """<div class="v3"><div class="v3-l">
<div><div style="margin-bottom:14px"><span class="segm"><span class="on">1 · Describe</span><span data-go="3b" style="cursor:pointer">2 · Explore</span></span></div><div class="w-h1">What matters to you?</div><div class="w-sub">Describe it in your own words. We turn it into preferences you can see and adjust.</div></div>
<div><div class="v3-sec"><span class="n">1</span>Your ideal internship<span>Write freely</span></div>
<div class="v3-ta"><p>A <mark>product or strategy</mark> internship in <mark>fintech</mark>, ideally <mark>London or Singapore</mark>, where I can <mark>learn from senior PMs</mark>. It has to be <mark>paid</mark>, <mark>6 months from January</mark>.<span class="cur"></span></p></div>
<div class="v3-und"><span class="l"><svg width="12" height="12" viewBox="0 0 16 16"><path d="M8 2.2 9.3 6.7 13.8 8 9.3 9.3 8 13.8 6.7 9.3 2.2 8 6.7 6.7z" fill="#0071E3"/></svg>We understood</span>
<span class="v3-p"><small>Role</small>Product, Strategy</span><span class="v3-p"><small>Industry</small>Fintech</span><span class="v3-p"><small>Where</small>London, Singapore</span><span class="v3-p"><small>Value</small>Mentorship</span><span class="v3-p m"><small>Must</small>Paid</span><span class="v3-p"><small>When</small>6 mo · Jan 2027</span></div>
<div class="v3-goal"><span class="k">In 3 years I want to be</span><b>Product Manager in fintech</b><span class="h">Roles that build toward it rank higher</span></div></div>
<div><div class="v3-sec"><span class="n">2</span>How much each one matters<span>Must-haves filter roles · the rest shape your ranking</span></div>
<div class="v3-tb"><div class="v3-r"><div class="k">Paid internship</div><div class="v3-seg"><span class="on must">Must have</span><span class="">Important</span><span class="">Nice to have</span><span class="">Don’t mind</span></div></div><div class="v3-r"><div class="k">Learning & mentorship<small>senior PMs, structured programme</small></div><div class="v3-seg"><span class="">Must have</span><span class="on imp">Important</span><span class="">Nice to have</span><span class="">Don’t mind</span></div></div><div class="v3-r"><div class="k">Fintech industry</div><div class="v3-seg"><span class="">Must have</span><span class="on imp">Important</span><span class="">Nice to have</span><span class="">Don’t mind</span></div></div><div class="v3-r"><div class="k">London or Singapore<small>hybrid preferred</small></div><div class="v3-seg"><span class="">Must have</span><span class="on imp">Important</span><span class="">Nice to have</span><span class="">Don’t mind</span></div></div><div class="v3-r"><div class="k">Return-offer potential</div><div class="v3-seg"><span class="">Must have</span><span class="">Important</span><span class="on">Nice to have</span><span class="">Don’t mind</span></div></div><div class="v3-r"><div class="k">Hybrid work<small>2–3 days in office</small></div><div class="v3-seg"><span class="">Must have</span><span class="">Important</span><span class="on">Nice to have</span><span class="">Don’t mind</span></div></div><div class="v3-r"><div class="k">Well-known brand</div><div class="v3-seg"><span class="">Must have</span><span class="">Important</span><span class="">Nice to have</span><span class="on">Don’t mind</span></div></div></div></div>
<div class="v3-el"><span class="t">Eligibility facts</span><span class="s">Checked by fixed rules, not by preferences</span><div class="sp"><span class="w-chip">Enrolled · Fudan</span><span class="w-chip">Graduates Jul 2027</span><span class="w-chip">Sponsorship · China, Singapore</span><span class="sel3 q">UK · not answered</span></div></div>
</div>
<div class="v3-r2"><div><div class="w-lab" style="margin-bottom:4px">Live preview</div><h3>Your preference profile</h3></div>
<div class="v3-box"><div class="v3-big"><b>312</b><span>roles fit · 41 unpaid removed by your must-have</span></div></div>
<div class="v3-box"><div class="w-lab">Preference fit is built from<span>Your weights</span></div>
<div class="v3-wb"><i style="flex:30;background:#0071E3;color:#fff">30%</i><i style="flex:25;background:#5AA2F0;color:#fff">25%</i><i style="flex:25;background:#A9CDF7;color:#0B3F7A">25%</i><i style="flex:12;background:#D6E7FB;color:#0B3F7A">12%</i><i style="flex:8;background:#EEF4FC;color:#0B3F7A">8%</i></div>
<div class="v3-wl"><span><i style="background:#0071E3"></i>Mentorship<b>30%</b></span><span><i style="background:#5AA2F0"></i>Fintech<b>25%</b></span><span><i style="background:#A9CDF7"></i>Location<b>25%</b></span><span><i style="background:#D6E7FB"></i>Return offer, hybrid<b>12%</b></span><span><i style="background:#EEF4FC;border:1px solid #D6E7FB"></i>Career goal<b>8%</b></span></div></div>
<div class="v3-box"><div class="w-lab">Example · how a role reads you<span>Preference fit</span></div>
<div style="display:flex;align-items:center;gap:12px"><span class="w-logo" style="background:#1D1D1F;width:34px;height:34px">RP</span><div style="flex:1"><div style="font-size:13.5px;font-weight:600">Product Analyst Intern</div><div style="font-size:12px;color:var(--t2)">Replai · London · Hybrid</div></div><span style="font-size:24px;font-weight:700;letter-spacing:-0.03em">88</span></div>
<div class="v3-ck"><div><svg width="12" height="12" viewBox="0 0 16 16"><path d="M3 8.5 6.3 12 13 4.5" stroke="#248A3D" stroke-width="2.2" fill="none" stroke-linecap="round"/></svg>Paid · £2,300 / month<span>must-have</span></div><div><svg width="12" height="12" viewBox="0 0 16 16"><path d="M3 8.5 6.3 12 13 4.5" stroke="#248A3D" stroke-width="2.2" fill="none" stroke-linecap="round"/></svg>PM mentorship programme<span>30%</span></div><div><svg width="12" height="12" viewBox="0 0 16 16"><path d="M3 8.5 6.3 12 13 4.5" stroke="#248A3D" stroke-width="2.2" fill="none" stroke-linecap="round"/></svg>Fintech<span>25%</span></div><div><svg width="12" height="12" viewBox="0 0 16 16"><path d="M3 8.5 6.3 12 13 4.5" stroke="#248A3D" stroke-width="2.2" fill="none" stroke-linecap="round"/></svg>London · hybrid<span>25%</span></div><div><svg width="12" height="12" viewBox="0 0 16 16"><circle cx="8" cy="8" r="6" stroke="#B25E09" stroke-width="1.6" fill="none"/><path d="M8 5v3.5M8 11h0" stroke="#B25E09" stroke-width="1.8" stroke-linecap="round"/></svg>Return offers not published<span>12%</span></div></div></div>
<div style="flex:1"></div><div class="w-tip"><svg width="16" height="16" viewBox="0 0 16 16" style="flex:none;margin-top:1px"><path d="M8 2 13.5 4v3.8c0 3-2.3 5.3-5.5 6.2-3.2-.9-5.5-3.2-5.5-6.2V4z" stroke="#0071E3" stroke-width="1.5" fill="none"/><path d="M5.7 8.2 7.3 9.8 10.4 6.5" stroke="#0071E3" stroke-width="1.5" fill="none" stroke-linecap="round"/></svg><div>Preferences only change the order. They never make you eligible or ineligible.</div></div>
</div></div>"""

S_3B = """<div class="sw"><div class="sw-c">
<div class="sw-top"><span class="segm"><span data-go="3a" style="cursor:pointer">1 · Describe</span><span class="on">2 · Explore</span></span><span class="sw-cnt"><b>Story 8 of 12</b> · about 1 minute left</span></div>
<div class="sw-pb"><i class="d"></i><i class="d"></i><i class="d"></i><i class="d"></i><i class="d"></i><i class="d"></i><i class="d"></i><i class="c"></i><i class=""></i><i class=""></i><i class=""></i><i class=""></i></div>
<div class="sw-stack"><div class="sw-cb b2"></div><div class="sw-cb b1"></div>
<div class="sw-card"><span class="stamp">I’D ENJOY THIS</span>
<div class="cd-tags"><span class="w-b ne">Product analytics</span><span class="w-b ne">Fintech</span></div>
<div class="cd-time">A Tuesday, 10:40</div>
<div class="cd-h">Conversion dropped overnight. You’re the first to notice.</div>
<div class="cd-p">You write a quick SQL query and find the drop is Android-only. By 2 pm you brief the PM with one chart and a clear next step.</div>
<div class="cd-viz"><div style="display:flex;justify-content:space-between;font-size:11.5px;color:var(--t2)"><span>Checkout conversion · last 7 days</span><span style="color:#C4302B;font-weight:600">−4.1% · Android only</span></div>
<svg width="100%" height="70" viewBox="0 0 480 70" preserveAspectRatio="none" style="margin-top:8px"><polyline points="0,22 70,20 140,24 210,19 280,21 350,23 400,52 480,50" fill="none" stroke="#AEAEB2" stroke-width="2"/><polyline points="0,30 70,28 140,31 210,27 280,29 350,30 400,30 480,29" fill="none" stroke="#0071E3" stroke-width="2"/><circle cx="400" cy="52" r="4" fill="#fff" stroke="#C4302B" stroke-width="2"/></svg>
<div style="display:flex;gap:14px;font-size:11px;color:var(--t3);margin-top:4px"><span style="display:flex;align-items:center;gap:5px"><i style="width:10px;height:2px;background:#AEAEB2;display:block"></i>Android</span><span style="display:flex;align-items:center;gap:5px"><i style="width:10px;height:2px;background:#0071E3;display:block"></i>iOS</span></div></div>
<div class="cd-sk"><span class="k">You’d use</span><span class="w-chip">SQL</span><span class="w-chip">Data analysis</span><span class="w-chip">Clear communication</span></div>
<div class="cd-why"><svg width="12" height="12" viewBox="0 0 16 16"><path d="M8 2.2 9.3 6.7 13.8 8 9.3 9.3 8 13.8 6.7 9.3 2.2 8 6.7 6.7z" fill="#0071E3"/></svg><span>Why this story: your CV mentions <b>SQL</b> and a <b>fintech product internship</b></span></div>
</div></div>
<div class="acts">
<div class="act"><span class="o"><svg width="20" height="20" viewBox="0 0 16 16"><path d="M4 4l8 8M12 4l-8 8" stroke="#6E6E73" stroke-width="1.8" stroke-linecap="round"/></svg></span>Not for me<kbd>←</kbd></div>
<div class="act sm"><span class="o"><svg width="16" height="16" viewBox="0 0 16 16"><path d="M6 6a2 2 0 1 1 2.8 1.8c-.5.3-.8.7-.8 1.3v.4M8 12h0" stroke="#6E6E73" stroke-width="1.7" fill="none" stroke-linecap="round"/></svg></span>Not sure<kbd>↑</kbd></div>
<div class="act yes"><span class="o"><svg width="22" height="22" viewBox="0 0 16 16"><path d="M8 13.5S2.5 10.2 2.5 6.3A2.8 2.8 0 0 1 8 5a2.8 2.8 0 0 1 5.5 1.3C13.5 10.2 8 13.5 8 13.5z" fill="#30A14E"/></svg></span>I’d enjoy this<kbd>→</kbd></div>
</div></div>
<div class="sw-r"><div><div class="w-lab" style="margin-bottom:4px">Live · from 7 swipes</div><h3>What we’re learning about you</h3></div>
<div class="v3-box" style="padding:12px 14px 6px"><div class="w-lab">Interests<span>Holland RIASEC</span></div><div style="display:flex;justify-content:center"><svg width="370" height="246" viewBox="0 0 380 246"><polygon points="190.0,91.3 216.6,106.7 216.6,137.3 190.0,152.7 163.4,137.3 163.4,106.7" fill="none" stroke="#E5E5EA" stroke-width="1"/><polygon points="190.0,60.7 243.1,91.3 243.1,152.7 190.0,183.3 136.9,152.7 136.9,91.3" fill="none" stroke="#E5E5EA" stroke-width="1"/><polygon points="190.0,30.0 269.7,76.0 269.7,168.0 190.0,214.0 110.3,168.0 110.3,76.0" fill="none" stroke="#E5E5EA" stroke-width="1"/><line x1="190" y1="122" x2="190.0" y2="30.0" stroke="#EFEFF2"/><line x1="190" y1="122" x2="269.7" y2="76.0" stroke="#EFEFF2"/><line x1="190" y1="122" x2="269.7" y2="168.0" stroke="#EFEFF2"/><line x1="190" y1="122" x2="190.0" y2="214.0" stroke="#EFEFF2"/><line x1="190" y1="122" x2="110.3" y2="168.0" stroke="#EFEFF2"/><line x1="190" y1="122" x2="110.3" y2="76.0" stroke="#EFEFF2"/><polygon points="190.0,105.4 260.1,81.5 215.5,136.7 190.0,163.4 132.6,155.1 143.8,95.3" fill="rgba(0,113,227,.12)" stroke="#0071E3" stroke-width="1.8" stroke-linejoin="round"/><circle cx="190.0" cy="105.4" r="3" fill="#0071E3"/><circle cx="260.1" cy="81.5" r="3" fill="#0071E3"/><circle cx="215.5" cy="136.7" r="3" fill="#0071E3"/><circle cx="190.0" cy="163.4" r="3" fill="#0071E3"/><circle cx="132.6" cy="155.1" r="3" fill="#0071E3"/><circle cx="143.8" cy="95.3" r="3" fill="#0071E3"/><text x="190.0" y="18.0" text-anchor="middle" font-size="11.5" font-weight="500" fill="#6E6E73" font-family="-apple-system,Inter,sans-serif">Realistic</text><text x="283.5" y="72.0" text-anchor="start" font-size="11.5" font-weight="700" fill="#1D1D1F" font-family="-apple-system,Inter,sans-serif">Investigative</text><text x="283.5" y="180.0" text-anchor="start" font-size="11.5" font-weight="500" fill="#6E6E73" font-family="-apple-system,Inter,sans-serif">Artistic</text><text x="190.0" y="234.0" text-anchor="middle" font-size="11.5" font-weight="500" fill="#6E6E73" font-family="-apple-system,Inter,sans-serif">Social</text><text x="96.5" y="180.0" text-anchor="end" font-size="11.5" font-weight="700" fill="#1D1D1F" font-family="-apple-system,Inter,sans-serif">Enterprising</text><text x="96.5" y="72.0" text-anchor="end" font-size="11.5" font-weight="500" fill="#6E6E73" font-family="-apple-system,Inter,sans-serif">Conventional</text></svg></div></div>
<div class="v3-box"><div class="w-lab">How you like to work<span>Work design</span></div>
<div class="bp"><span>Structured</span><span class="tr"><i style="left:70%"></i></span><span><b>Open-ended</b></span></div>
<div class="bp"><span>Solo focus</span><span class="tr"><i style="left:58%"></i></span><span>Team</span></div>
<div class="bp"><span>Steady pace</span><span class="tr"><i style="left:78%"></i></span><span><b>Fast feedback</b></span></div>
<div class="bp"><span><b>Depth</b></span><span class="tr"><i style="left:34%"></i></span><span>Variety</span></div></div>
<div><div class="w-lab">Your last swipes</div><div class="hist"><span class="y">✓ Pricing analysis</span><span class="n">✕ Client audit</span><span class="y">✓ Launch review</span><span class="n">✕ Cold-call sales</span><span class="y">✓ Market sizing</span></div></div>
<div class="v3-box"><div class="w-lab">Emerging direction<span>Updates each swipe</span></div><div style="font-size:14px;font-weight:620">Product analytics · Strategy</div><div style="font-size:12px;color:var(--t2);margin-top:3px">New role type to consider: <b style="color:var(--blue);font-weight:600">Growth Analyst</b> · 9 open roles</div></div>
<div style="flex:1"></div>
<div class="w-tip"><svg width="16" height="16" viewBox="0 0 16 16" style="flex:none;margin-top:1px"><path d="M8 2 13.5 4v3.8c0 3-2.3 5.3-5.5 6.2-3.2-.9-5.5-3.2-5.5-6.2V4z" stroke="#0071E3" stroke-width="1.5" fill="none"/><path d="M5.7 8.2 7.3 9.8 10.4 6.5" stroke="#0071E3" stroke-width="1.5" fill="none" stroke-linecap="round"/></svg><div>This is for you, not employers. It adjusts your Preference fit only — you review it before it’s used.</div></div>
</div></div>"""

S_4 = """<div class="a4"><div class="a4-l">
<div class="w-h1">Analyzing roles for you</div>
<div class="w-sub">We read each job posting, check your eligibility, then rank what’s left. <b>About 20 seconds.</b></div>
<div class="fun">
<div class="f4"><div class="k">Roles in catalog<small>Updated today</small></div><div class="f4b"><i style="width:100%;background:#D1D1D6"></i></div><div class="n">1,284</div></div>
<div class="f4"><div class="k">Match your preferences<small>Role type, location, dates</small></div><div class="f4b"><i style="width:24.3%;background:#AEAEB2"></i></div><div class="n">312</div></div>
<div class="f4"><div class="k">Checked for eligibility<small>Mandatory requirements</small></div><div class="f4b"><i style="width:6.1%;background:#6E6E73"></i></div><div class="n">78</div></div>
<div class="f4"><div class="k">Eligibility result<small>Fixed rules</small></div><div class="f4b" style="background:none"><i style="flex:38;background:#30A14E;border-radius:6px"></i><i style="flex:17;background:#E3A03A;border-radius:6px"></i><i style="flex:23;background:repeating-linear-gradient(135deg,#F3C9C5 0 3px,#FBEAE8 3px 6px);border-radius:6px"></i></div><div class="n">78</div></div>
<div class="lg4"><span><i style="background:#30A14E"></i>38 eligible</span><span><i style="background:#E3A03A"></i>17 to verify</span><span><i style="background:#F3C9C5"></i>23 excluded · conflict</span></div>
<div class="f4"><div class="k">Ranked for you<small>Eligible + to verify</small></div><div class="f4b"><i style="width:70.5%;background:var(--blue);border-radius:9px"></i></div><div class="n" style="color:var(--blue)">55</div></div>
</div></div>
<div class="a4-r"><div class="w-lab">Progress<span>Live</span></div>
<div class="p4">
<div class="p4-r"><span class="c" style="background:#30A14E"><svg width="10" height="10" viewBox="0 0 16 16"><path d="M3 8.5 6.3 12 13 4.5" stroke="#fff" stroke-width="2.6" fill="none" stroke-linecap="round" stroke-linejoin="round"/></svg></span><div><div class="t">Read job requirements</div><div class="s">AI extracts requirements from 312 postings</div></div><span class="tg w-b ne">AI</span></div>
<div class="p4-r"><span class="c" style="background:#30A14E"><svg width="10" height="10" viewBox="0 0 16 16"><path d="M3 8.5 6.3 12 13 4.5" stroke="#fff" stroke-width="2.6" fill="none" stroke-linecap="round" stroke-linejoin="round"/></svg></span><div><div class="t">Sort into 8 fixed criteria</div><div class="s">Location, visa, degree, language…</div></div><span class="tg w-b ne">AI</span></div>
<div class="p4-r"><span class="c" style="background:#30A14E"><svg width="10" height="10" viewBox="0 0 16 16"><path d="M3 8.5 6.3 12 13 4.5" stroke="#fff" stroke-width="2.6" fill="none" stroke-linecap="round" stroke-linejoin="round"/></svg></span><div><div class="t">Check eligibility</div><div class="s">78 roles · 23 conflicts removed</div></div><span class="tg w-b" style="color:var(--blue);background:var(--blueBg)">Rules</span></div>
<div class="p4-r"><span class="spin"></span><div><div class="t">Rank 55 roles</div><div class="s">Profile, preference, urgency, freshness</div></div><span class="tg w-b" style="color:var(--blue);background:var(--blueBg)">Rules</span></div>
</div>
<div class="w-card" style="padding:16px 18px"><div class="w-lab">First results<span>Updating</span></div>
<div style="display:flex;align-items:center;gap:12px"><span class="w-logo" style="background:#8E8E93;width:34px;height:34px">NE</span><div style="flex:1"><div style="font-size:13.5px;font-weight:600">Strategy Intern</div><div style="font-size:12px;color:var(--t2)">Nestella · Singapore</div></div><span style="font-size:22px;font-weight:700;letter-spacing:-0.03em">76</span></div>
<div style="display:flex;align-items:center;gap:12px;margin-top:12px"><span class="w-logo" style="background:#AEAEB2;width:34px;height:34px">JP</span><div style="flex:1"><div style="font-size:13.5px;font-weight:600">Strategy Analyst Intern</div><div style="font-size:12px;color:var(--t2)">J.P. Morrow · Singapore</div></div><span style="font-size:22px;font-weight:700;letter-spacing:-0.03em">74</span></div></div>
<div class="w-tip"><svg width="16" height="16" viewBox="0 0 16 16" style="flex:none;margin-top:1px"><path d="M8 2 13.5 4v3.8c0 3-2.3 5.3-5.5 6.2-3.2-.9-5.5-3.2-5.5-6.2V4z" stroke="#0071E3" stroke-width="1.5" fill="none"/><path d="M5.7 8.2 7.3 9.8 10.4 6.5" stroke="#0071E3" stroke-width="1.5" fill="none" stroke-linecap="round"/></svg><div>AI only reads postings. Eligibility and ranking are decided by fixed rules — same inputs, same result.</div></div>
</div></div>"""

S_5 = """<div class="cr"><div class="cr-h"><div class="w-h1">Building your shortlist</div><div class="w-sub" id="cr-sub">Checking your top matches one by one · <b>1 of 5</b></div></div>
<div class="cr-row" id="cr-row"><div class="cc "><div class="cc-scan"><i></i></div><div class="cc-top"><span class="w-logo" style="background:#8E8E93;width:44px;height:44px">NE</span><div style="flex:1"><div class="cc-t">Strategy Intern</div><div class="cc-m">Nestella · Singapore · Onsite</div></div><span class="w-b ok"><i></i>Eligible</span></div>
<div class="cc-sc"><b>76<small>/100</small></b><span style="font-size:12px;color:var(--amber);font-weight:600"></span></div><div class="cc-bar"><i style="flex:31.2;background:#0071E3"></i><i style="flex:20.5;background:#5AA2F0"></i><i style="flex:13.0;background:#A9CDF7"></i><i style="flex:11.2;background:#D6E7FB"></i><i style="flex:24.0"></i></div>
<div class="cc-ck"><div><svg width="12" height="12" viewBox="0 0 16 16"><path d="M3 8.5 6.3 12 13 4.5" stroke="#248A3D" stroke-width="2.2" fill="none" stroke-linecap="round"/></svg><span>Strategy internship</span></div><div><svg width="12" height="12" viewBox="0 0 16 16"><path d="M3 8.5 6.3 12 13 4.5" stroke="#248A3D" stroke-width="2.2" fill="none" stroke-linecap="round"/></svg><span>Mandarin HSK 4</span></div></div><div class="cc-ft"><div class="cc-pill u">Closes in 9 days<small>3 Oct</small></div><div class="cc-pill">5 days ago<small>Verified today</small></div></div></div><div class="cc "><div class="cc-scan"><i></i></div><div class="cc-top"><span class="w-logo" style="background:#AEAEB2;width:44px;height:44px">JP</span><div style="flex:1"><div class="cc-t">Strategy Analyst Intern</div><div class="cc-m">J.P. Morrow · Singapore · Hybrid</div></div><span class="w-b ok"><i></i>Eligible</span></div>
<div class="cc-sc"><b>74<small>/100</small></b><span style="font-size:12px;color:var(--amber);font-weight:600"></span></div><div class="cc-bar"><i style="flex:32.0;background:#0071E3"></i><i style="flex:19.0;background:#5AA2F0"></i><i style="flex:10.0;background:#A9CDF7"></i><i style="flex:13.8;background:#D6E7FB"></i><i style="flex:25.2"></i></div>
<div class="cc-ck"><div><svg width="12" height="12" viewBox="0 0 16 16"><path d="M3 8.5 6.3 12 13 4.5" stroke="#248A3D" stroke-width="2.2" fill="none" stroke-linecap="round"/></svg><span>SQL, Python</span></div><div><svg width="12" height="12" viewBox="0 0 16 16"><path d="M3 8.5 6.3 12 13 4.5" stroke="#248A3D" stroke-width="2.2" fill="none" stroke-linecap="round"/></svg><span>MSc Finance</span></div><div><svg width="12" height="12" viewBox="0 0 16 16"><circle cx="8" cy="8" r="6" stroke="#B25E09" stroke-width="1.6" fill="none"/><path d="M8 5v3.5M8 11h0" stroke="#B25E09" stroke-width="1.8" stroke-linecap="round"/></svg><span>No A/B testing experience</span></div></div><div class="cc-ft"><div class="cc-pill">Closes 30 Oct<small></small></div><div class="cc-pill">Posted today<small>Verified today</small></div></div></div><div class="cc "><div class="cc-scan"><i></i></div><div class="cc-top"><span class="w-logo" style="background:#1D1D1F;width:44px;height:44px">RP</span><div style="flex:1"><div class="cc-t">Product Analyst Intern</div><div class="cc-m">Replai · London · Hybrid</div></div><span class="w-b am"><i></i>To verify</span></div>
<div class="cc-sc"><b>72<small>/100</small></b><span style="font-size:12px;color:var(--amber);font-weight:600">87 − 15 until verified</span></div><div class="cc-bar"><i style="flex:36.8;background:#0071E3"></i><i style="flex:22.0;background:#5AA2F0"></i><i style="flex:18.0;background:#A9CDF7"></i><i style="flex:10.5;background:#D6E7FB"></i><i style="flex:12.7"></i></div>
<div class="cc-ck"><div><svg width="12" height="12" viewBox="0 0 16 16"><path d="M3 8.5 6.3 12 13 4.5" stroke="#248A3D" stroke-width="2.2" fill="none" stroke-linecap="round"/></svg><span>7 of 8 key skills</span></div><div><svg width="12" height="12" viewBox="0 0 16 16"><path d="M3 8.5 6.3 12 13 4.5" stroke="#248A3D" stroke-width="2.2" fill="none" stroke-linecap="round"/></svg><span>MSc Finance · fintech internship</span></div><div><svg width="12" height="12" viewBox="0 0 16 16"><circle cx="8" cy="8" r="6" stroke="#B25E09" stroke-width="1.6" fill="none"/><path d="M8 5v3.5M8 11h0" stroke="#B25E09" stroke-width="1.8" stroke-linecap="round"/></svg><span>UK work permission unknown</span></div></div><div class="cc-ft"><div class="cc-pill u">Closes in 3 days<small>27 Sep</small></div><div class="cc-pill">9 days ago<small>Verified today</small></div></div><div class="cc-need"><svg width="12" height="12" viewBox="0 0 16 16"><circle cx="8" cy="8" r="6" stroke="#B25E09" stroke-width="1.6" fill="none"/><path d="M8 5v3.5M8 11h0" stroke="#B25E09" stroke-width="1.8" stroke-linecap="round"/></svg>One answer from you could make this your #1</div></div><div class="cc "><div class="cc-scan"><i></i></div><div class="cc-top"><span class="w-logo" style="background:#3A3A3C;width:44px;height:44px">BC</span><div style="flex:1"><div class="cc-t">Strategy Intern</div><div class="cc-m">Bolton Consulting Group · London · Onsite</div></div><span class="w-b am"><i></i>To verify</span></div>
<div class="cc-sc"><b>68<small>/100</small></b><span style="font-size:12px;color:var(--amber);font-weight:600">83 − 15 until verified</span></div><div class="cc-bar"><i style="flex:34.0;background:#0071E3"></i><i style="flex:22.5;background:#5AA2F0"></i><i style="flex:12.0;background:#A9CDF7"></i><i style="flex:14.2;background:#D6E7FB"></i><i style="flex:17.2"></i></div>
<div class="cc-ck"><div><svg width="12" height="12" viewBox="0 0 16 16"><path d="M3 8.5 6.3 12 13 4.5" stroke="#248A3D" stroke-width="2.2" fill="none" stroke-linecap="round"/></svg><span>Strong fit with your preferences</span></div><div><svg width="12" height="12" viewBox="0 0 16 16"><circle cx="8" cy="8" r="6" stroke="#B25E09" stroke-width="1.6" fill="none"/><path d="M8 5v3.5M8 11h0" stroke="#B25E09" stroke-width="1.8" stroke-linecap="round"/></svg><span>UK work permission unknown</span></div></div><div class="cc-ft"><div class="cc-pill">Closes 15 Oct<small></small></div><div class="cc-pill">2 days ago<small>Verified today</small></div></div><div class="cc-need"><svg width="12" height="12" viewBox="0 0 16 16"><circle cx="8" cy="8" r="6" stroke="#B25E09" stroke-width="1.6" fill="none"/><path d="M8 5v3.5M8 11h0" stroke="#B25E09" stroke-width="1.8" stroke-linecap="round"/></svg>Same answer unlocks this role</div></div><div class="cc "><div class="cc-scan"><i></i></div><div class="cc-top"><span class="w-logo" style="background:#636366;width:44px;height:44px">RO</span><div style="flex:1"><div class="cc-t">Product Intern</div><div class="cc-m">Roshe · Shanghai · Hybrid</div></div><span class="w-b ok"><i></i>Eligible</span></div>
<div class="cc-sc"><b>66<small>/100</small></b><span style="font-size:12px;color:var(--amber);font-weight:600"></span></div><div class="cc-bar"><i style="flex:29.6;background:#0071E3"></i><i style="flex:17.5;background:#5AA2F0"></i><i style="flex:9.6;background:#A9CDF7"></i><i style="flex:12.8;background:#D6E7FB"></i><i style="flex:30.5"></i></div>
<div class="cc-ck"><div><svg width="12" height="12" viewBox="0 0 16 16"><path d="M3 8.5 6.3 12 13 4.5" stroke="#248A3D" stroke-width="2.2" fill="none" stroke-linecap="round"/></svg><span>Fintech internship</span></div><div><svg width="12" height="12" viewBox="0 0 16 16"><path d="M3 8.5 6.3 12 13 4.5" stroke="#248A3D" stroke-width="2.2" fill="none" stroke-linecap="round"/></svg><span>Based in Shanghai</span></div><div><svg width="12" height="12" viewBox="0 0 16 16"><circle cx="8" cy="8" r="6" stroke="#B25E09" stroke-width="1.6" fill="none"/><path d="M8 5v3.5M8 11h0" stroke="#B25E09" stroke-width="1.8" stroke-linecap="round"/></svg><span>Prefers CS degree</span></div></div><div class="cc-ft"><div class="cc-pill">Closes 20 Oct<small></small></div><div class="cc-pill">3 days ago<small>Verified today</small></div></div></div></div>
<div class="slots" id="cr-slots"></div></div>"""

S_6 = """<div class="c6"><div class="c6-col">
<div class="c6-pr">1 question · about 10 seconds</div>
<div class="w-h1">Can you work in the UK without visa sponsorship?</div>
<div class="w-sub">It isn’t in your CV, and it’s the only thing still deciding <b>14 roles in London</b>.</div>
<div class="c6-lg"><span class="w-logo" style="background:#1D1D1F;width:26px;height:26px">RP</span><span class="w-logo" style="background:#3A3A3C;width:26px;height:26px">BC</span><span class="w-logo" style="background:#48484A;width:26px;height:26px">LZ</span><span class="w-logo" style="background:#636366;width:26px;height:26px">MS</span><span class="m">Replai, Bolton Consulting Group, Lazarde &amp; Co. and 11 more</span></div>
<div class="op">
<div class="o6 on"><span class="rd"></span><div><div class="t">Yes, I can work in the UK</div><div class="s">UK/Irish citizen, settled status or a valid work visa</div></div><span class="fx" style="color:var(--green)">+11 roles</span></div>
<div class="o6"><span class="rd"></span><div><div class="t">No, I’d need sponsorship</div><div class="s">We’ll keep only roles that sponsor visas</div></div><span class="fx" style="color:var(--amber)">4 roles stay</span></div>
<div class="o6"><span class="rd"></span><div><div class="t">I’m not sure</div><div class="s">Roles stay marked “to verify” for now</div></div><span class="fx" style="color:var(--t3);font-weight:500">No change</span></div>
</div>
<div class="fld">Saved as <b>Work authorization · UK</b> — one predefined field in your profile.</div>
</div></div>
<div class="c6-r"><div><div class="w-lab" style="margin-bottom:4px">Live preview</div><h3>If you answer “Yes”</h3></div>
<div class="st6"><div><div class="l">Eligible roles</div><div class="v"><s>38</s>49<small>+11</small></div></div><div><div class="l">To verify</div><div class="v"><s>17</s>6</div></div></div>
<div><div class="w-lab">New top 5</div><div class="mini"><div class="mr nw"><span class="p">1</span><span class="w-logo" style="background:#1D1D1F;width:28px;height:28px">RP</span><div><div class="nm">Product Analyst Intern</div><div class="co">Replai · London</div></div><span class="mv" style="color:var(--green)">↑ 2</span></div><div class="mr nw"><span class="p">2</span><span class="w-logo" style="background:#3A3A3C;width:28px;height:28px">BC</span><div><div class="nm">Strategy Intern</div><div class="co">Bolton Consulting Group · London</div></div><span class="mv" style="color:var(--green)">↑ 2</span></div><div class="mr nw"><span class="p">3</span><span class="w-logo" style="background:#48484A;width:28px;height:28px">LZ</span><div><div class="nm">Business Analyst Intern</div><div class="co">Lazarde &amp; Co. · London</div></div><span class="mv" style="color:var(--green)">New</span></div><div class="mr nw"><span class="p">4</span><span class="w-logo" style="background:#636366;width:28px;height:28px">MS</span><div><div class="nm">Product Intern</div><div class="co">Morgan Stanfield · London</div></div><span class="mv" style="color:var(--green)">New</span></div><div class="mr"><span class="p">5</span><span class="w-logo" style="background:#8E8E93;width:28px;height:28px">NE</span><div><div class="nm">Strategy Intern</div><div class="co">Nestella · Singapore</div></div><span class="mv" style="color:var(--t3)">↓ 4</span></div></div></div>
<div style="flex:1"></div>
<div class="w-tip"><svg width="16" height="16" viewBox="0 0 16 16" style="flex:none;margin-top:1px"><path d="M8 2 13.5 4v3.8c0 3-2.3 5.3-5.5 6.2-3.2-.9-5.5-3.2-5.5-6.2V4z" stroke="#0071E3" stroke-width="1.5" fill="none"/><path d="M5.7 8.2 7.3 9.8 10.4 6.5" stroke="#0071E3" stroke-width="1.5" fill="none" stroke-linecap="round"/></svg><div>Eligibility and ranking are recalculated by fixed rules from this one field.</div></div>
</div>"""

S_7 = """<div class="f7"><div class="f7-top"><div><div class="w-h1">Your priorities</div><div class="w-sub">Your answer unlocked 11 roles. <b>Start with Replai — it closes in 3 days.</b></div></div>
<div class="s5-sum"><div class="s5-k"><div class="l">Eligible</div><div class="v">49<small>+11</small></div></div><div class="s5-k"><div class="l">To verify</div><div class="v" style="color:var(--amber)">6</div></div><div class="s5-k"><div class="l">Excluded</div><div class="v" style="color:var(--t3)">23</div></div></div></div>
<div class="f7-flt"><span class="segm"><span class="on">All 5</span><span>Closing this week · 2</span><span>New · 2</span></span>
<div class="chg2"><svg width="13" height="13" viewBox="0 0 16 16"><path d="M10.5 2.5l3 3L6 13H3v-3z" stroke="#6E6E73" stroke-width="1.5" fill="none" stroke-linejoin="round"/></svg>Work authorization · UK <span style="color:var(--t3);text-decoration:line-through">Unknown</span> → <span class="w-b ok">Yes</span><span style="color:var(--t3);margin-left:8px">Recalculated 09:12</span></div></div>
<div class="f7-list"><div class="it top"><div class="it-rk">1<small style="color:var(--green)">↑ 2</small></div><div class="it-sc"><svg width="64" height="64" viewBox="0 0 64 64"><circle cx="32" cy="32" r="27" stroke="#EDEDF0" stroke-width="5" fill="none"/><circle cx="32" cy="32" r="27" stroke="#0071E3" stroke-width="5" fill="none" stroke-linecap="round" stroke-dasharray="147.6 169.6" transform="rotate(-90 32 32)"/></svg><b>87</b></div>
<div class="it-main"><span class="w-logo" style="background:#1D1D1F;width:40px;height:40px">RP</span><div style="min-width:0"><div class="it-t">Product Analyst Intern</div><div class="it-m">Replai · London · Hybrid · Eligible</div></div></div><div class="it-ln"><span class="ig"><svg width="12" height="12" viewBox="0 0 16 16"><path d="M3 8.5 6.3 12 13 4.5" stroke="#248A3D" stroke-width="2.2" fill="none" stroke-linecap="round"/></svg>7 of 8 key skills</span><span class="in">No gaps found</span></div>
<div class="dt"><span class="cal u"><i>SEP</i><b>27</b></span><div><div class="k u">Closes in 3 days</div><small>Apply this week</small></div></div>
<div class="fs"><span class="d" style="background:#E3A03A"></span><div>9 days ago<small>Verified today</small></div></div>
<div class="btn">Start application</div></div><div class="it"><div class="it-rk">2<small style="color:var(--green)">↑ 2</small></div><div class="it-sc"><svg width="64" height="64" viewBox="0 0 64 64"><circle cx="32" cy="32" r="27" stroke="#EDEDF0" stroke-width="5" fill="none"/><circle cx="32" cy="32" r="27" stroke="#0071E3" stroke-width="5" fill="none" stroke-linecap="round" stroke-dasharray="140.8 169.6" transform="rotate(-90 32 32)"/></svg><b>83</b></div>
<div class="it-main"><span class="w-logo" style="background:#3A3A3C;width:40px;height:40px">BC</span><div style="min-width:0"><div class="it-t">Strategy Intern</div><div class="it-m">Bolton Consulting Group · London · Onsite · Eligible</div></div></div><div class="it-ln"><span class="ig"><svg width="12" height="12" viewBox="0 0 16 16"><path d="M3 8.5 6.3 12 13 4.5" stroke="#248A3D" stroke-width="2.2" fill="none" stroke-linecap="round"/></svg>Strong preference fit</span><span class="in">No gaps found</span></div>
<div class="dt"><span class="cal"><i>OCT</i><b>15</b></span><div><div class="k">Closes 15 Oct</div><small>21 days left</small></div></div>
<div class="fs"><span class="d" style="background:#30A14E"></span><div>2 days ago<small>Verified today</small></div></div>
<div class="btn">Open</div></div><div class="it"><div class="it-rk">3<small style="color:var(--green)">New</small></div><div class="it-sc"><svg width="64" height="64" viewBox="0 0 64 64"><circle cx="32" cy="32" r="27" stroke="#EDEDF0" stroke-width="5" fill="none"/><circle cx="32" cy="32" r="27" stroke="#0071E3" stroke-width="5" fill="none" stroke-linecap="round" stroke-dasharray="137.4 169.6" transform="rotate(-90 32 32)"/></svg><b>81</b></div>
<div class="it-main"><span class="w-logo" style="background:#48484A;width:40px;height:40px">LZ</span><div style="min-width:0"><div class="it-t">Business Analyst Intern</div><div class="it-m">Lazarde &amp; Co. · London · Hybrid · Eligible</div></div></div><div class="it-ln"><span class="ig"><svg width="12" height="12" viewBox="0 0 16 16"><path d="M3 8.5 6.3 12 13 4.5" stroke="#248A3D" stroke-width="2.2" fill="none" stroke-linecap="round"/></svg>SQL, Python</span><span class="ix"><svg width="12" height="12" viewBox="0 0 16 16"><circle cx="8" cy="8" r="6" stroke="#B25E09" stroke-width="1.6" fill="none"/><path d="M8 5v3.5M8 11h0" stroke="#B25E09" stroke-width="1.8" stroke-linecap="round"/></svg>No payments experience</span></div>
<div class="dt"><span class="cal"><i>OCT</i><b>18</b></span><div><div class="k">Closes 18 Oct</div><small>24 days left</small></div></div>
<div class="fs"><span class="d" style="background:#30A14E"></span><div>5 days ago<small>Verified today</small></div></div>
<div class="btn">Open</div></div><div class="it"><div class="it-rk">4<small style="color:var(--green)">New</small></div><div class="it-sc"><svg width="64" height="64" viewBox="0 0 64 64"><circle cx="32" cy="32" r="27" stroke="#EDEDF0" stroke-width="5" fill="none"/><circle cx="32" cy="32" r="27" stroke="#0071E3" stroke-width="5" fill="none" stroke-linecap="round" stroke-dasharray="130.6 169.6" transform="rotate(-90 32 32)"/></svg><b>77</b></div>
<div class="it-main"><span class="w-logo" style="background:#636366;width:40px;height:40px">MS</span><div style="min-width:0"><div class="it-t">Product Intern</div><div class="it-m">Morgan Stanfield · London · Hybrid · Eligible</div></div></div><div class="it-ln"><span class="ig"><svg width="12" height="12" viewBox="0 0 16 16"><path d="M3 8.5 6.3 12 13 4.5" stroke="#248A3D" stroke-width="2.2" fill="none" stroke-linecap="round"/></svg>Product internship</span><span class="ix"><svg width="12" height="12" viewBox="0 0 16 16"><circle cx="8" cy="8" r="6" stroke="#B25E09" stroke-width="1.6" fill="none"/><path d="M8 5v3.5M8 11h0" stroke="#B25E09" stroke-width="1.8" stroke-linecap="round"/></svg>Prefers 12 months</span></div>
<div class="dt"><span class="cal"><i>OCT</i><b>20</b></span><div><div class="k">Closes 20 Oct</div><small>26 days left</small></div></div>
<div class="fs"><span class="d" style="background:#30A14E"></span><div>Posted today<small>Verified today</small></div></div>
<div class="btn">Open</div></div><div class="it"><div class="it-rk">5<small style="color:var(--t3)">↓ 4</small></div><div class="it-sc"><svg width="64" height="64" viewBox="0 0 64 64"><circle cx="32" cy="32" r="27" stroke="#EDEDF0" stroke-width="5" fill="none"/><circle cx="32" cy="32" r="27" stroke="#0071E3" stroke-width="5" fill="none" stroke-linecap="round" stroke-dasharray="128.9 169.6" transform="rotate(-90 32 32)"/></svg><b>76</b></div>
<div class="it-main"><span class="w-logo" style="background:#8E8E93;width:40px;height:40px">NE</span><div style="min-width:0"><div class="it-t">Strategy Intern</div><div class="it-m">Nestella · Singapore · Onsite · Eligible</div></div></div><div class="it-ln"><span class="ig"><svg width="12" height="12" viewBox="0 0 16 16"><path d="M3 8.5 6.3 12 13 4.5" stroke="#248A3D" stroke-width="2.2" fill="none" stroke-linecap="round"/></svg>Mandarin HSK 4</span><span class="in">No gaps found</span></div>
<div class="dt"><span class="cal u"><i>OCT</i><b>3</b></span><div><div class="k u">Closes in 9 days</div><small>Apply this week</small></div></div>
<div class="fs"><span class="d" style="background:#30A14E"></span><div>5 days ago<small>Verified today</small></div></div>
<div class="btn">Open</div></div></div></div>"""

